### ISSUE TITLE
Gapps

### ISSUE THREAD

**Issue by CanKolay3499** [j7b3y/treble_pb#1]
Can you release a gapps version?

**Comment by j7b3y** [comment]
Since Gapps is a Google product and not part of the Android platform, we plan to release vanilla ROMs only.
If you need Gapps, we recommend installing it another way.
We apologize for not meeting your expectations.

**Comment by iful17** [comment]
and can you release vndklite version?

**Comment by j7b3y** [comment]
Released converted using [sas-creator](https://github.com/AndyCGYan/sas-creator).

**Comment by j7b3y** [comment]
published gapps build.
[here](https://sourceforge.net/projects/any-artifact/files/GSI/ProjectBlaze/v1.4_415/)
