### ISSUE TITLE
Gapps

### ISSUE THREAD

**Issue by GuraNotFound** [j7b3y/treble_pb#2]
no Gapps version? I want the Gapps version!

**Comment by j7b3y** [comment]
Gapps is a Google product and not part of AOSP, so we were reluctant to include it, but demand for Gapps exceeded our expectations.
I'm thinking of releasing a Gapps build or installing Gapps in a vanilla build.

**Comment by CanKolay3499** [comment]
> Gapps is a Google product and not part of AOSP, so we were reluctant to include it, but demand for Gapps exceeded our expectations. I'm thinking of releasing a Gapps build or installing Gapps in a vanilla build.

Which gapps you should to use in this gsi?

**Comment by j7b3y** [comment]
published gapps build.
[here](https://sourceforge.net/projects/any-artifact/files/GSI/ProjectBlaze/v1.4_415/)
