### ISSUE TITLE
SafetyNet

### ISSUE THREAD

**Issue by Phyan** [j7b3y/treble_pb#8]
### Inquiry content

Is it possible to somehow make SafetyNet certification on this firmware? I tried all sorts of ways to solve this problem (SafetyNet Fix, Hideprops, MagiskHide and so on), but nothing worked :(
Does not pass both CTS profile and Basic Integrity. Evaluation type: BASIC
Would be grateful for any help, thanks

### Device name

Xiaomi Redmi Note 5 Pro (Whyred) - Vendor: DerpFest 12L (22.08.22)

### Select ROM type

vndklite

### installed-mods

Magisk, NikGapps (omni)

**Comment by j7b3y** [comment]
Should probably be fixed in 1.5-EOL as found [here](https://t.me/projectblaze/45825)

**Comment by Phyan** [comment]
> Should probably be fixed in 1.5-EOL as found [here](https://t.me/projectblaze/45825)

Oh, glad to hear it, but my device is not officially supported, so the only solution for now is GSI. So it's interesting to hear if you want to do it? Would be grateful for any answer, thank you

**Comment by j7b3y** [comment]
It's late, but I'm uploading it now that the 1.5-EOL build is complete.
Devices that worked with 1.4 should probably work. (Operation confirmed on Huawei P30)
